#define FUNC_DIAGNOSTIC 8
#define SUB_FUNC_ECHO 0
#define READ_COIL 1
#define READ_DISCRETE_INPUT 2
#define READ_HOLDING_REGISTER 3
#define READ_INPUT_REGISTER 4
#define WRITE_SINGLE_COIL 5
#define WRITE_SINGLE_REGISTER 6
